#!/usr/bin/env bash
# install.sh — installs speckit-autopilot skills globally for Claude Code
# and creates a speckit-autopilot binary in ~/.local/bin/
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_DIR="$SCRIPT_DIR/skills"
DEST_BASE="$HOME/.claude/skills"
BIN_DIR="$HOME/.local/bin"
BIN_PATH="$BIN_DIR/speckit-autopilot"
RUN_MJS="$SCRIPT_DIR/run.mjs"

echo "Installing speckit-autopilot..."
echo "  Source : $SCRIPT_DIR"
echo "  Skills : $DEST_BASE"
echo "  Binary : $BIN_PATH"
echo ""

# ── Skills ──────────────────────────────────────────────────────────────────

for src in "$SOURCE_DIR"/*.md; do
  skill=$(basename "$src" .md)
  dest_dir="$DEST_BASE/$skill"
  dest_file="$dest_dir/SKILL.md"

  mkdir -p "$dest_dir"

  # Write frontmatter + content
  {
    echo "---"
    echo "name: $skill"
    echo "description: speckit-autopilot $skill"
    echo "---"
    echo ""
    cat "$src"
  } > "$dest_file"

  echo "  /$skill  →  $dest_file"
done

# ── Binary ───────────────────────────────────────────────────────────────────

mkdir -p "$BIN_DIR"

cat > "$BIN_PATH" << BINEOF
#!/usr/bin/env bash
# speckit-autopilot — generated by install.sh
exec node "$RUN_MJS" "\$@"
BINEOF

chmod +x "$BIN_PATH"
echo ""
echo "  speckit-autopilot binary → $BIN_PATH"

# ── PATH hint ────────────────────────────────────────────────────────────────

if ! echo "$PATH" | grep -q "$BIN_DIR"; then
  echo ""
  echo "  NOTE: $BIN_DIR is not in your PATH."
  echo "  Add this to your ~/.zshrc or ~/.bashrc:"
  echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
fi

echo ""
echo "Done. Restart Claude Code to pick up the updated skills."
