import { Feature, Backlog, priorityWeight } from "./backlog-schema.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface RoadmapEpic {
  name: string;
  features: Feature[];
}

export interface RoadmapDocument {
  generatedAt: string;
  epics: RoadmapEpic[];
  orderedFeatures: Feature[];
  notes: string[];
}

// ---------------------------------------------------------------------------
// Topological sort (Kahn's algorithm)
// ---------------------------------------------------------------------------

export function topologicalSort(features: Feature[]): Feature[] {
  const idToFeature = new Map<string, Feature>(features.map((f) => [f.id, f]));
  const inDegree = new Map<string, number>(features.map((f) => [f.id, 0]));
  const adj = new Map<string, string[]>(features.map((f) => [f.id, []]));

  for (const f of features) {
    for (const dep of f.dependsOn) {
      const list = adj.get(dep);
      if (list) list.push(f.id);
      inDegree.set(f.id, (inDegree.get(f.id) ?? 0) + 1);
    }
  }

  // Seed queue with nodes having no dependencies, sorted by priority desc then original index
  const queue: string[] = features
    .filter((f) => (inDegree.get(f.id) ?? 0) === 0)
    .sort((a, b) => priorityWeight(b.priority) - priorityWeight(a.priority))
    .map((f) => f.id);

  const result: Feature[] = [];

  while (queue.length > 0) {
    const id = queue.shift()!;
    const feature = idToFeature.get(id);
    if (feature) result.push(feature);

    const neighbours = adj.get(id) ?? [];
    const ready: string[] = [];
    for (const nId of neighbours) {
      const deg = (inDegree.get(nId) ?? 1) - 1;
      inDegree.set(nId, deg);
      if (deg === 0) ready.push(nId);
    }
    // Sort ready neighbours by priority desc before adding.
    // All IDs in ready are guaranteed to be in idToFeature (built from the same features array).
    ready.sort((a, b) =>
      priorityWeight(idToFeature.get(b)!.priority) -
      priorityWeight(idToFeature.get(a)!.priority)
    );
    queue.push(...ready);
  }

  return result;
}

// ---------------------------------------------------------------------------
// Grouping
// ---------------------------------------------------------------------------

export function groupByEpic(features: Feature[]): RoadmapEpic[] {
  const epicMap = new Map<string, Feature[]>();
  for (const f of features) {
    const list = epicMap.get(f.epic) ?? [];
    list.push(f);
    epicMap.set(f.epic, list);
  }
  return Array.from(epicMap.entries()).map(([name, feats]) => ({ name, features: feats }));
}

// ---------------------------------------------------------------------------
// Markdown renderer
// ---------------------------------------------------------------------------

export function renderRoadmapMarkdown(doc: RoadmapDocument): string {
  const lines: string[] = [
    "# Product Roadmap",
    "",
    `Generated by speckit-autopilot on ${doc.generatedAt}`,
    "",
    "## Epics",
    "",
  ];

  for (const epic of doc.epics) {
    lines.push(`### ${epic.name}`);
    for (const f of epic.features) {
      lines.push(`- **${f.id}** ${f.title} (${f.priority} priority, ${f.estimatedComplexity} complexity)`);
    }
    lines.push("");
  }

  lines.push("## Feature Implementation Order", "");
  lines.push("| # | ID | Feature | Epic | Priority | Status | Depends On |");
  lines.push("|---|----|---------|----- |----------|--------|------------|");

  for (let i = 0; i < doc.orderedFeatures.length; i++) {
    const f = doc.orderedFeatures[i];
    const deps = f.dependsOn.length > 0 ? f.dependsOn.join(", ") : "—";
    lines.push(`| ${i + 1} | ${f.id} | ${f.title} | ${f.epic} | ${f.priority} | ${f.status} | ${deps} |`);
  }

  if (doc.notes.length > 0) {
    lines.push("", "## Notes", "");
    for (const note of doc.notes) {
      lines.push(`- ${note}`);
    }
  }

  lines.push("");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------

export function generateRoadmap(backlog: Backlog): RoadmapDocument {
  const ordered = topologicalSort(backlog.features);
  const epics = groupByEpic(ordered);
  const notes: string[] = [];

  // Detect cycles (features that didn't make it into the sort)
  if (ordered.length < backlog.features.length) {
    const sortedIds = new Set(ordered.map((f) => f.id));
    const skipped = backlog.features.filter((f) => !sortedIds.has(f.id));
    notes.push(`WARNING: ${skipped.length} feature(s) have circular dependencies and were omitted from the order: ${skipped.map((f) => f.id).join(", ")}`);
  }

  return {
    generatedAt: backlog.generatedAt,
    epics,
    orderedFeatures: ordered,
    notes,
  };
}
